apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    link.argocd.argoproj.io/external-link: http://192.168.0.183:30001
spec:
  project: default
  source:
    repoURL: ssh://git@git.blox.media:222/matt/k8s-apps.git
    path: overlays/lain-k3s-draft/uptime-kuma
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
